[package]
name = "mael"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
ulid = { version = "1.2.1", features = ["serde"] }
